name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
  build-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: build-cli
        run: |
          make build-cli
  test:
    strategy:
      fail-fast: false
      matrix:
        go: ["1.14", "1.15", "tip"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        if: matrix.go != 'tip'
        with:
          go-version: ${{ matrix.go }}
      - name: install tip
        if: matrix.go == 'tip'
        run: |
          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
          cd $HOME/gotip/src
          ./make.bash
          echo "GOROOT=$HOME/gotip" >> "$GITHUB_ENV"
          echo "$HOME/gotip/bin" >> "$GITHUB_PATH"
      - name: test
        run: |
          go version
          go env
          make test COVERAGE_DIR=/tmp/coverage
      - uses: codecov/codecov-action@v1
        with:
          file: /tmp/coverage/combined.txt
